import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Respiratory Sound Classification\n",
            "This notebook trains a 4-class respiratory sound classifier (Normal, Crackle, Wheeze, Both) using the ICBHI 2017 dataset.\n",
            "\n",
            "## Requirements\n",
            "`pip install librosa numpy pandas scikit-learn tensorflow matplotlib seaborn jupyter`\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import os\n",
            "import glob\n",
            "import librosa\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import seaborn as sns\n",
            "import pickle\n",
            "import warnings\n",
            "from tqdm.notebook import tqdm\n",
            "\n",
            "from sklearn.model_selection import KFold\n",
            "from sklearn.ensemble import RandomForestClassifier\n",
            "from sklearn.metrics import classification_report, confusion_matrix, accuracy_score\n",
            "\n",
            "import tensorflow as tf\n",
            "from tensorflow.keras.models import Sequential, Model\n",
            "from tensorflow.keras.layers import Dense, Conv1D, MaxPooling1D, Flatten, Dropout, Bidirectional, LSTM, Input, Multiply, Activation, GlobalAveragePooling1D\n",
            "from tensorflow.keras.utils import to_categorical\n",
            "\n",
            "warnings.filterwarnings('ignore')\n",
            "print('TensorFlow version:', tf.__version__)\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 1. Data Loading and Preprocessing\n",
            "Load the ICBHI dataset, split recordings into respiratory cycles using annotations, and extract features."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Configuration\n",
            "DATASET_PATH = './archive'  # UPDATE THIS to your ICBHI dataset unzipped folder path containing the .txt and .wav files\n",
            "SR = 16000\n",
            "N_MFCC = 36\n",
            "N_FFT = 400\n",
            "HOP_LENGTH = 160\n",
            "MAX_AUDIO_LEN = 5 * SR  # 5 seconds fixed length for padding/truncating\n",
            "\n",
            "labels_dict = {\n",
            "    (0, 0): 0, # Normal\n",
            "    (1, 0): 1, # Crackle\n",
            "    (0, 1): 2, # Wheeze\n",
            "    (1, 1): 3  # Both\n",
            "}\n",
            "classes = ['Normal', 'Crackle', 'Wheeze', 'Both']\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def extract_features(audio_segment):\n",
            "    \"\"\"\n",
            "    Extracts features for a given audio segment padding/truncating to a fixed length.\n",
            "    \"\"\"\n",
            "    # Pad or truncate\n",
            "    if len(audio_segment) > MAX_AUDIO_LEN:\n",
            "        y = audio_segment[:MAX_AUDIO_LEN]\n",
            "    else:\n",
            "        y = librosa.util.fix_length(audio_segment, size=MAX_AUDIO_LEN)\n",
            "        \n",
            "    # 1. 36 MFCCs\n",
            "    mfccs = librosa.feature.mfcc(y=y, sr=SR, n_mfcc=N_MFCC, n_fft=N_FFT, hop_length=HOP_LENGTH)\n",
            "    \n",
            "    # 2. Spectral features\n",
            "    cent = librosa.feature.spectral_centroid(y=y, sr=SR, n_fft=N_FFT, hop_length=HOP_LENGTH)\n",
            "    rolloff = librosa.feature.spectral_rolloff(y=y, sr=SR, n_fft=N_FFT, hop_length=HOP_LENGTH)\n",
            "    contrast = librosa.feature.spectral_contrast(y=y, sr=SR, n_fft=N_FFT, hop_length=HOP_LENGTH)\n",
            "    \n",
            "    # 3. ZCR and RMS Energy\n",
            "    zcr = librosa.feature.zero_crossing_rate(y=y, frame_length=N_FFT, hop_length=HOP_LENGTH)\n",
            "    rms = librosa.feature.rms(y=y, frame_length=N_FFT, hop_length=HOP_LENGTH)\n",
            "    \n",
            "    # 4. Chroma features\n",
            "    chroma = librosa.feature.chroma_stft(y=y, sr=SR, n_fft=N_FFT, hop_length=HOP_LENGTH)\n",
            "    \n",
            "    # Concatenate all features along the feature axis (axis 0)\n",
            "    # Shape: (features, time_steps)\n",
            "    features = np.vstack([mfccs, cent, rolloff, contrast, zcr, rms, chroma])\n",
            "    \n",
            "    # Transpose to (time_steps, features) for CNN/LSTM\n",
            "    return features.T\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def load_dataset(dataset_path):\n",
            "    X = []\n",
            "    y = []\n",
            "    txt_files = glob.glob(os.path.join(dataset_path, '*.txt'))\n",
            "    if len(txt_files) == 0:\n",
            "        print(\"No .txt files found. Please ensure DATASET_PATH points to the directory containing .txt and .wav files.\")\n",
            "        return np.array([]), np.array([])\n",
            "        \n",
            "    for txt_file in tqdm(txt_files, desc=\"Processing files\"):\n",
            "        wav_file = txt_file.replace('.txt', '.wav')\n",
            "        if not os.path.exists(wav_file):\n",
            "            continue\n",
            "            \n",
            "        try:\n",
            "            audio, _ = librosa.load(wav_file, sr=SR)\n",
            "        except Exception as e:\n",
            "            print(f\"Error loading {wav_file}: {e}\")\n",
            "            continue\n",
            "            \n",
            "        annotations = pd.read_csv(txt_file, sep='\\t', header=None, names=['start', 'end', 'crackles', 'wheezes'])\n",
            "        \n",
            "        for _, row in annotations.iterrows():\n",
            "            start_samp = int(row['start'] * SR)\n",
            "            end_samp = int(row['end'] * SR)\n",
            "            \n",
            "            # Extract cycle\n",
            "            cycle_audio = audio[start_samp:end_samp]\n",
            "            if len(cycle_audio) == 0:\n",
            "                continue\n",
            "                \n",
            "            label = labels_dict.get((int(row['crackles']), int(row['wheezes'])), 0)\n",
            "            \n",
            "            features = extract_features(cycle_audio)\n",
            "            X.append(features)\n",
            "            y.append(label)\n",
            "            \n",
            "    return np.array(X), np.array(y)\n",
            "\n",
            "# Uncomment this to actually process the data (if dataset is present)\n",
            "# X_data, y_data = load_dataset(DATASET_PATH)\n",
            "# print(f\"Loaded {len(X_data)} cycles.\")\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Model Architectures\n",
            "We define building functions for Random Forest (baseline), 1D CNN, and BiLSTM with Attention."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# For Random Forest, we flatten the features (or take mean over time)\n",
            "def get_rf_features(X):\n",
            "    # X shape: (samples, time_steps, features)\n",
            "    # We take the mean across time_steps to get (samples, features)\n",
            "    return np.mean(X, axis=1)\n",
            "\n",
            "def build_cnn(input_shape, num_classes=4):\n",
            "    model = Sequential([\n",
            "        Input(shape=input_shape),\n",
            "        Conv1D(64, kernel_size=3, activation='relu', padding='same'),\n",
            "        MaxPooling1D(pool_size=2),\n",
            "        Conv1D(128, kernel_size=3, activation='relu', padding='same'),\n",
            "        MaxPooling1D(pool_size=2),\n",
            "        Conv1D(256, kernel_size=3, activation='relu', padding='same'),\n",
            "        MaxPooling1D(pool_size=2),\n",
            "        GlobalAveragePooling1D(),\n",
            "        Dropout(0.5),\n",
            "        Dense(128, activation='relu'),\n",
            "        Dense(num_classes, activation='softmax')\n",
            "    ])\n",
            "    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n",
            "    return model\n",
            "\n",
            "\n",
            "class AttentionLayer(tf.keras.layers.Layer):\n",
            "    def __init__(self, **kwargs):\n",
            "        super(AttentionLayer, self).__init__(**kwargs)\n",
            "\n",
            "    def build(self, input_shape):\n",
            "        self.W = self.add_weight(name='attention_weight', \n",
            "                                 shape=(input_shape[-1], 1), \n",
            "                                 initializer='random_normal', \n",
            "                                 trainable=True)\n",
            "        self.b = self.add_weight(name='attention_bias', \n",
            "                                 shape=(input_shape[1], 1), \n",
            "                                 initializer='zeros', \n",
            "                                 trainable=True)\n",
            "        super(AttentionLayer, self).build(input_shape)\n",
            "\n",
            "    def call(self, x):\n",
            "        # x: (batch_size, time_steps, features)\n",
            "        e = tf.keras.backend.tanh(tf.keras.backend.dot(x, self.W) + self.b)\n",
            "        a = tf.keras.backend.softmax(e, axis=1)\n",
            "        output = x * a\n",
            "        return tf.keras.backend.sum(output, axis=1)\n",
            "\n",
            "def build_bilstm_attention(input_shape, num_classes=4):\n",
            "    inputs = Input(shape=input_shape)\n",
            "    x = Bidirectional(LSTM(128, return_sequences=True))(inputs)\n",
            "    x = Dropout(0.3)(x)\n",
            "    x = Bidirectional(LSTM(64, return_sequences=True))(x)\n",
            "    x = AttentionLayer()(x)\n",
            "    x = Dense(64, activation='relu')(x)\n",
            "    x = Dropout(0.4)(x)\n",
            "    outputs = Dense(num_classes, activation='softmax')(x)\n",
            "    \n",
            "    model = Model(inputs, outputs)\n",
            "    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])\n",
            "    return model\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. 5-Fold Cross Validation & Training\n",
            "We will evaluate each model using 5-Fold CV and save the best performing one."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# To run this cell correctly, you need actual data in X_data and y_data.\n",
            "def run_training_experiment(X, y):\n",
            "    kf = KFold(n_splits=5, shuffle=True, random_state=42)\n",
            "    \n",
            "    rf_accuracies, cnn_accuracies, lstm_accuracies = [], [], []\n",
            "    \n",
            "    best_lstm_model = None\n",
            "    best_cnn_model = None\n",
            "    best_rf_model = None\n",
            "    best_overall_acc = 0\n",
            "    best_model_name = \"\"\n",
            "    \n",
            "    y_cat = to_categorical(y, num_classes=4)\n",
            "    X_rf = get_rf_features(X)\n",
            "    input_shape = (X.shape[1], X.shape[2])\n",
            "    \n",
            "    fold = 1\n",
            "    for train_index, test_index in kf.split(X):\n",
            "        print(f\"\\n--- Fold {fold} ---\")\n",
            "        # Splits\n",
            "        X_train, X_test = X[train_index], X[test_index]\n",
            "        y_train, y_test = y[train_index], y[test_index]\n",
            "        y_train_cat, y_test_cat = y_cat[train_index], y_cat[test_index]\n",
            "        \n",
            "        X_train_rf, X_test_rf = X_rf[train_index], X_rf[test_index]\n",
            "        \n",
            "        # 1. Random Forest\n",
            "        rf = RandomForestClassifier(n_estimators=100, random_state=42)\n",
            "        rf.fit(X_train_rf, y_train)\n",
            "        rf_preds = rf.predict(X_test_rf)\n",
            "        rf_acc = accuracy_score(y_test, rf_preds)\n",
            "        rf_accuracies.append(rf_acc)\n",
            "        if rf_acc > best_overall_acc:\n",
            "            best_overall_acc = rf_acc\n",
            "            best_rf_model = rf\n",
            "            best_model_name = \"RandomForest\"\n",
            "            \n",
            "        # 2. 1D CNN\n",
            "        cnn = build_cnn(input_shape)\n",
            "        cnn.fit(X_train, y_train_cat, epochs=30, batch_size=32, verbose=0, validation_split=0.1)\n",
            "        cnn_preds = np.argmax(cnn.predict(X_test, verbose=0), axis=1)\n",
            "        cnn_acc = accuracy_score(y_test, cnn_preds)\n",
            "        cnn_accuracies.append(cnn_acc)\n",
            "        if cnn_acc > best_overall_acc:\n",
            "            best_overall_acc = cnn_acc\n",
            "            best_cnn_model = cnn\n",
            "            best_model_name = \"1D_CNN\"\n",
            "            \n",
            "        # 3. BiLSTM Attention\n",
            "        lstm = build_bilstm_attention(input_shape)\n",
            "        lstm.fit(X_train, y_train_cat, epochs=30, batch_size=32, verbose=0, validation_split=0.1)\n",
            "        lstm_preds = np.argmax(lstm.predict(X_test, verbose=0), axis=1)\n",
            "        lstm_acc = accuracy_score(y_test, lstm_preds)\n",
            "        lstm_accuracies.append(lstm_acc)\n",
            "        if lstm_acc > best_overall_acc:\n",
            "            best_overall_acc = lstm_acc\n",
            "            best_lstm_model = lstm\n",
            "            best_model_name = \"BiLSTM_Attention\"\n",
            "            \n",
            "        print(f\"Fold {fold} Accuracies -> RF: {rf_acc:.4f}, CNN: {cnn_acc:.4f}, BiLSTM: {lstm_acc:.4f}\")\n",
            "        \n",
            "        # Print Fold 5 results as representative\n",
            "        if fold == 5:\n",
            "            print(\"\\nClassification Report (BiLSTM - Fold 5):\")\n",
            "            print(classification_report(y_test, lstm_preds, target_names=classes))\n",
            "            \n",
            "            cm = confusion_matrix(y_test, lstm_preds)\n",
            "            plt.figure(figsize=(6,5))\n",
            "            sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=classes, yticklabels=classes)\n",
            "            plt.title('BiLSTM Confusion Matrix - Fold 5')\n",
            "            plt.ylabel('True')\n",
            "            plt.xlabel('Predicted')\n",
            "            plt.show()\n",
            "\n",
            "        fold += 1\n",
            "        \n",
            "    print(\"\\n=== Cross-Validation Results ===\")\n",
            "    print(f\"Random Forest - Mean Acc: {np.mean(rf_accuracies):.4f} (+/- {np.std(rf_accuracies):.4f})\")\n",
            "    print(f\"1D CNN        - Mean Acc: {np.mean(cnn_accuracies):.4f} (+/- {np.std(cnn_accuracies):.4f})\")\n",
            "    print(f\"BiLSTM        - Mean Acc: {np.mean(lstm_accuracies):.4f} (+/- {np.std(lstm_accuracies):.4f})\")\n",
            "    print(f\"\\nBest Model: {best_model_name} with {best_overall_acc:.4f} accuracy\")\n",
            "    \n",
            "    return best_rf_model, best_cnn_model, best_lstm_model, best_model_name\n",
            "\n",
            "# Run experiment if data is loaded\n",
            "# best_rf, best_cnn, best_lstm, top_model = run_training_experiment(X_data, y_data)\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Exporting the Best Model\n",
            "Save the best performing model to `.tflite` for mobile deployment and slightly modify to `.pkl` for quick backend serving (if utilizing ML standard libraries like sklearn)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "def save_models(best_rf, best_dl_model):\n",
            "    print(\"Saving models...\")\n",
            "    \n",
            "    # 1. Save Random Forest as .pkl for FastAPI backend\n",
            "    if best_rf:\n",
            "        with open('respiratory_rf_model.pkl', 'wb') as f:\n",
            "            pickle.dump(best_rf, f)\n",
            "        print(\"Saved RF model to 'respiratory_rf_model.pkl'\")\n",
            "        \n",
            "    # 2. Save DL model as .tflite for Mobile deployment\n",
            "    if best_dl_model:\n",
            "        converter = tf.lite.TFLiteConverter.from_keras_model(best_dl_model)\n",
            "        # Optimize for size and latency\n",
            "        converter.optimizations = [tf.lite.Optimize.DEFAULT]\n",
            "        tflite_model = converter.convert()\n",
            "        \n",
            "        with open('respiratory_dl_model.tflite', 'wb') as f:\n",
            "            f.write(tflite_model)\n",
            "        print(\"Saved Deep Learning model to 'respiratory_dl_model.tflite'\")\n",
            "\n",
            "# Uncomment after training to save\n",
            "# best_dl = best_lstm if np.mean(lstm_accuracies) > np.mean(cnn_accuracies) else best_cnn\n",
            "# save_models(best_rf, best_dl)\n"
        ]
    }
]

notebook = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": {
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "cells": cells
}

with open("train_respiratory_model.ipynb", "w") as f:
    json.dump(notebook, f, indent=4)

print("Created train_respiratory_model.ipynb")
